name: "Alpha actions."
on:
  push:
    branches-ignore:
      - master
      - dev
jobs:
  deploy-blog:
    name: Deploying the blog to alpha.suntprogramator.dev
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download Hugo static site generator
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
      - name: Install Hugo static site generator
        run: sudo dpkg -i hugo_extended_0.74.3_Linux-64bit.deb
      - name: Resolve the dependency errors
        run: sudo apt-get install -f
      - name: Build blog
        run: hugo
      - name: Deploy blog 
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_URL }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "public"
          remoteDir: "www/alpha.suntprogramator.dev"